In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.3'

In [3]:
import pandas as pd

In [4]:
pd.__version__

'1.3.2'

In [6]:
car = pd.read_csv("data.csv")

In [7]:
car.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [11]:
car[car['Make']=='BMW']['MSRP'].mean()

61546.76347305389

In [18]:
car[car['Year'] >= 2015]['Engine HP'].isna().sum()

51

In [20]:
meanofengine = car['Engine HP'].mean()
meanofengine

249.38607007176023

In [23]:
car['Engine HP'].fillna(value=meanofengine, inplace=True)

In [25]:
car['Engine HP'].mean()

249.38607007176

In [27]:
car['Engine HP'].isna().sum()

0

In [29]:
car1 = car[car['Make']=='Rolls-Royce'][["Engine HP", "Engine Cylinders", "highway MPG"]]

In [34]:
car1 = car1.drop_duplicates()

In [44]:
car1

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [45]:
X = car1.to_numpy()

In [46]:
X

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [47]:
XTX = np.dot(X.T, X)

In [48]:
XTX_invert = np.linalg.inv(XTX) 

In [49]:
XTX_invert

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [50]:
XTX_invert.sum()

0.032212320677486195

In [51]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [52]:
w = XTX_invert.dot(X.T).dot(y)

In [53]:
w

array([ 0.19989598, 31.02612262, 31.65378877])